FROM eclipse-temurin:25-jre
WORKDIR /app
COPY target/*.jar /app/app.jar

EXPOSE 1905
EXPOSE 5005

ENTRYPOINT ["java",
  "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
  "-jar","/app/app.jar"
]